### ISSUE TITLE
[Proposal] Godot Engine

### ISSUE THREAD

**Issue by nonunknown** [ThePhysicsGuys/Physics3D#1]
Hi I'm a godot engine user, the devs posted that they need someone (for hire) to rewrite physics engine:

https://www.reddit.com/r/godot/comments/hqhxcm/lets_talk_about_the_actual_approach_for_move_and/ (see reduzio answer)

I was thinking if you can help them, since the head developer is focused on vulkan.

you can contact him on twitter: @reduzio

**Comment by VonTum** [comment]
Hello there! 

I've read through some of the physics documentation of godot, and it is quite similar to what we're building. Though it is a very interesting proposal, I do not wish to abandon this project over it. 

That does however give us the idea to start working towards compatibility of our engine with GDNative, so that perhaps one day Physics3D could be used with Godot instead.

**Comment by nonunknown** [comment]
its a cool idea, waiting for that dude thanks!!!
